spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  data:
    web:
      pageable:
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: create

    defer-datasource-initialization: true

    properties:
      hibernate:
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 80